image: php:7.2
cache:
  paths:
    - vendor/
    - composer.phar

variables:
  COMPOSER_ALLOW_SUPERUSER: 1

before_script:
  - apt-get update -yqq && apt-get install git -yqq
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

.test: &test
  artifacts:
    paths:
      - coverage_report
  script:
    - phpdbg -qrr vendor/bin/phpunit --debug -vvv --bootstrap vendor/autoload.php --coverage-text --coverage-html coverage_report --colors=never --whitelist src/ tests
  stage: test

test:php7.2:
  <<: *test

test:php7.3:
  image: php:7.3
  <<: *test

test:php7.4:
  image: php:7.4-rc
  <<: *test